name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to GCP
      run: |
        ssh -o StrictHostKeyChecking=no web-app@34.72.145.222 << 'EOF'
        cd /var/www/html/
        # Copy the HTML file from the GitHub repo to the web server's root directory
        cp ~/gcp-labs/lab01/gcp-lab.html /var/www/html/
        sudo systemctl restart nginx
        EOF
